### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by tafaust** [MrEfrem/auditdeps#1]
I am running `yarn dlx @efrem/auditdeps` and get the following error:

```
undefined:1
<h1>Redirect...</h1>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at BrotliDecompress.returnResults (/tmp/xfs-0a68ef49/dlx-9839/node_modules/@efrem/auditdeps/dist/utils/http.js:106:28)
    at BrotliDecompress.emit (events.js:400:28)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

My yarn version is 3.1.1

**Comment by MrEfrem** [comment]
You should use built-in `yarn npm audit` instead.
